### ISSUE TITLE
Is it possible to set own slug strategy?

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-lucid-slugify#11] opened 2019-01-17 20:39 UTC
Hi! Need possibility to register to Strategies own function. Thanks

**Comment by RomainLanz** [comment] 2019-01-18 12:33
Duplicate of https://github.com/adonisjs/adonis-lucid-slugify/issues/9

**Closed by RomainLanz** 2019-01-18 12:33 UTC
Labels: triage

**Comment by yariksav** [comment] 2019-01-18 12:40
Sorry, @RomainLanz  but I suppose this issue is not duplication of #9 
I asked is it possible to register own strategy function, for example I need to assign slug depends of record id, like id=201, slug='0000000201', etc, this is possible only afterCreate record

**Comment by RomainLanz** [comment] 2019-01-18 12:41
Have you checked the documentation about **Defining custom strategies**?
https://github.com/adonisjs/adonis-lucid-slugify#defining-custom-strategies-

**Comment by yariksav** [comment] 2019-01-18 12:43
Thank you very much, @RomainLanz!

**Comment by yariksav** [comment] 2019-01-18 12:50
Sorry, i've occasionally deleted previous comment, but It is still actual to have slug depends of record ID. It's possible only in afterCreate hook. If it not actual for this package - I've made this by hooks directly. Thank you again ;)
